language: python
before_install:
- sudo apt-get update
- sudo apt-get install nodejs npm
- npm install stylus -g
install:
- pip install stylus
python:
- '2.7'
deploy:
  provider: pypi
  user: dalou
  password:
    secure: iO8xcY0LTFOtPOHt7McujR0GQzTjfaGrxa2EeV9v1BmvfAm0DNfW6Itbu59pnVbVhPfPUnPKycMn6pNBiUL0pm3Ergfaz4zIMFHLgGMQ1BiIdZUOCFtI/gF12nA9viM/lQEfxWj72RKTUBodB/QtGjMFnhMbC2Vs4Ji7W0HNyZslDeQ/PuhGfoSIIRxzDSNrK+07pLB0zmC2yS/GLyxPLlF6ifflHhSexpuyPITFNW9DZV8BML+aviuqSaAKQe1dURXQSy8KEnQr96gGuPHYyxxS1Y8JZ/+cDwfNAg2b6DD8oY58wzN6ZeynjYP4PwP9j6La/AeWSzSlv8mbkS7yaYYJABUJwTi2Ay/OvKdCgahdytpzB4SSDWKfydOQNRTAdMphSnlT761ZFgHa9HJKt6ayG9bLg6ef6btMWX/1gJn3dO+IpNgnegNOCqqhnsb3ay0CiUEJ4filwgiSW9VQWHgzKixnjzmAdZLlpCQMFPkCWR0J1l5ojgSOK1cYauemT3i9R+eZlEkLNXui1xiFZFL6/y1KTsWyrXs4ybdtOX2lHal5qW+/aRHwgMSMLT8I7rNeBB/+Ca0i5F/IHdB1l/q/QOrIxOkjUr8eMwQ2qwrsGrDAjwF6IEuqd4M3dbmI6CnuktLPx+HOF1HniLwvnm+pJnJeHXeFm/9zzVGuxp4=

  on:
    branch: master