language: python
before_install:
- sudo apt-get update
- sudo apt-get install nodejs npm
- npm install stylus -g
install:
- pip install stylus
- pip install -q -e .
python:
- '2.7'
script:
- python runtests.py
deploy:
  provider: pypi
  user: dalou
  password:
    secure: VA4sFWwe424vACnma2j7F4j0Bth4cqRskNJJ5SzyxB46B0ZCE+5T28WGz2lRbY1f0ZBZHTILFCFhU5EfnB443avAzHrMbLJ+ARJ0FA+qonEEOpbJlXMxKyWBOSCvFDchrFEFlFvlenNGtB0nXGCmE31tKywJ2sS+OwNvZOFo6lg/v/258jzTc6EGqao1BFnt/gHL2A/5ESY7QGZsBszJlaFM1voFjBVH2kE1WqY55LQXheqAnbmnYH97Kdj8lasf3LMF1tyAncvIiFw0zk50ywjFmvN8J1uQc6hTxrKGL+v8WMoJowdMOqzXY/hkPa1iP24oexWZHg+0g/VQUN1ViQ23yMmdSWzSi9t77oCdji1kr6hGKRMmx0//ANqNiC8VFtxSyeHjnpdKnOpqCb7PJzuKmgXUtdSagFL8Dmqc4GQbmNYNRBuoS+MIkNgcVOBd3vMNxQq7VxssASOxK7wN15otI1/HsW1uExzfjpg5uMLQbG3cGasGyGtfo2DiMI4XaF7RK0Gng81OmyXZ8LLYq9pPmk/dz/0YI2zGtgQt22Z3mtoUkg3hW9R44HRopCxXPO775jKTsRSxDHB2J0Hq1yo6Cue6mIHX1oLRh3UtGPn6LoD3Cq86w80nStd4YZvCDpuQhVtM/Jjb+/3WkAb1Fpg3hPgI6MQvxw+iB8h8L8s=
  on:
    branch: all_branches
    tags: true
